"""PlatformIO extra script for LuxDMX-v2.

1. Fix toolchain PATH for toolchain-xtensa-esp-elf 14.2.0+ where binaries
   live in a nested subdirectory (xtensa-esp-elf/bin/) instead of the
   top-level bin/ the ESP-IDF CMake builder expects.
2. Generate PROGMEM header files from src/pages/*.html and src/assets/*
   into src/generated/*.h at build time.
"""
import os
import sys
import gzip

# ---------------------------------------------------------------------------
# 1. Toolchain PATH fix (module-level — os.environ.copy() in espidf.py picks it up)
# ---------------------------------------------------------------------------
# The toolchain-xtensa-esp-elf 14.2.0+ package nests binaries under
# xtensa-esp-elf/bin/ instead of the top-level bin/ the ESP-IDF CMake builder
# expects.  PlatformIO may install the package in either packages/ or tools/.
_pio_home = os.path.join(os.path.expanduser("~"), ".platformio")
for _base in ("packages", "tools"):
    _nested_bin = os.path.join(
        _pio_home, _base, "toolchain-xtensa-esp-elf", "xtensa-esp-elf", "bin"
    )
    if os.path.isdir(_nested_bin):
        _cur = os.environ.get("PATH", "")
        if _nested_bin not in _cur:
            os.environ["PATH"] = _nested_bin + os.pathsep + _cur
        print("  [extra_scripts] toolchain PATH fix: %s" % _nested_bin)
        break


# ---------------------------------------------------------------------------
# 2. Generate PROGMEM headers from HTML pages and binary assets
# ---------------------------------------------------------------------------
def _c_escape(data):
    """Format a bytes blob as a C uint8_t array initializer."""
    out = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        vals = ", ".join("0x%02x" % b for b in chunk)
        sep = "," if i + 16 < len(data) else ""
        out.append("    %s%s" % (vals, sep))
    return "\n".join(out)


def _gen_gz_header(src, dst, sym):
    with open(src, "rb") as f:
        data = gzip.compress(f.read(), mtime=0)
    len_sym = sym + "_LEN"
    with open(dst, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by extra_scripts.py -- do not edit.\n")
        f.write("// Source: %s (gzip)\n" % os.path.basename(src))
        f.write("#pragma once\n")
        f.write("#include <Arduino.h>\n\n")
        f.write("static const uint8_t %s[] = {\n" % sym)
        f.write(_c_escape(data) + "\n")
        f.write("};\n")
        f.write("const size_t %s = %d;\n" % (len_sym, len(data)))


def _gen_raw_html(src, dst, sym):
    with open(src, "r", encoding="utf-8") as f:
        text = f.read()
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    escaped = escaped.replace("\r", "\\r").replace("\n", "\\n")
    with open(dst, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by extra_scripts.py -- do not edit.\n")
        f.write("// Source: %s\n" % os.path.basename(src))
        f.write("#pragma once\n")
        f.write("#include <Arduino.h>\n\n")
        f.write('static const char %s[] = "%s";\n' % (sym, escaped))


def _gen_bin(src, dst, sym, gz):
    with open(src, "rb") as f:
        raw = f.read()
    data = gzip.compress(raw, mtime=0) if gz else raw
    len_sym = sym + "_LEN"
    enc = " (gzip)" if gz else ""
    with open(dst, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by extra_scripts.py -- do not edit.\n")
        f.write("// Source: %s%s\n" % (os.path.basename(src), enc))
        f.write("#pragma once\n")
        f.write("#include <Arduino.h>\n\n")
        f.write("static const uint8_t %s[] = {\n" % sym)
        f.write(_c_escape(data) + "\n")
        f.write("};\n")
        f.write("const size_t %s = %d;\n" % (len_sym, len(data)))


def _generate_headers(project_dir):
    pages = os.path.join(project_dir, "src", "pages")
    assets = os.path.join(project_dir, "src", "assets")
    gen = os.path.join(project_dir, "src", "generated")
    os.makedirs(gen, exist_ok=True)

    # Gzipped pages — symbol name, gzip flag
    gz_pages = [
        ("index.html",   "INDEX_HTML"),
        ("config.html",  "CONFIG_HTML"),
        ("rdm.html",     "RDM_HTML"),
    ]
    raw_pages = [
        ("config_saved.html", "CONFIG_SAVED_HTML"),
        ("setup.html",        "SETUP_HTML"),
        ("setup_done.html",   "SETUP_DONE_HTML"),
        ("reset.html",        "RESET_HTML"),
        ("reset_done.html",   "RESET_DONE_HTML"),
        ("ota_progress.html", "OTA_PROGRESS_HTML"),
        ("ota_done.html",     "OTA_DONE_HTML"),
    ]
    bin_assets = [
        ("logo.webp",         "LOGO_WEBP",         False),
        ("favicon.png",       "FAVICON_PNG",       False),
        ("bootstrap.min.css", "BOOTSTRAP_MIN_CSS", True),
    ]

    for name, sym in gz_pages:
        src = os.path.join(pages, name)
        if os.path.isfile(src):
            _gen_gz_header(src, os.path.join(gen, sym.lower() + ".h"), sym)
    for name, sym in raw_pages:
        src = os.path.join(pages, name)
        if os.path.isfile(src):
            _gen_raw_html(src, os.path.join(gen, sym.lower() + ".h"), sym)
    for name, sym, gz in bin_assets:
        src = os.path.join(assets, name)
        if os.path.isfile(src):
            _gen_bin(src, os.path.join(gen, sym.lower() + ".h"), sym, gz)

    # Generate config templates header
    tpl_script = os.path.join(project_dir, "tools", "gen_config_templates.py")
    if os.path.isfile(tpl_script):
        os.system('"{python}" "{script}" "{project}"'.format(
            python=sys.executable, script=tpl_script, project=project_dir))

    print("  [extra_scripts] generated PROGMEM headers in src/generated/")


# Resolve project dir: prefer SCons env, fall back to filesystem search.
_project_dir = None
try:
    Import("env")  # noqa: F821 — SCons builtin
    _project_dir = env.subst("$PROJECT_DIR")
    _pioenv = env.subst("$PIOENV")
except Exception:
    # Standalone or native env — find project root by walking up from CWD.
    _p = os.getcwd()
    while _p:
        if os.path.isfile(os.path.join(_p, "platformio.ini")):
            _project_dir = _p
            break
        _p = os.path.dirname(_p)

if _project_dir:
    _generate_headers(_project_dir)
