#include "web_frontend.h"
#include "common.h"

// Main index page HTML
static const char index_html[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"  <meta charset=\"UTF-8\">"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"  <title>LuxDMX Gateway</title>"
"  <link rel=\"stylesheet\" href=\"/assets/style.css\">"
"</head>"
"<body>"
"  <div class=\"container\">"
"    <header>"
"      <h1>LuxDMX Gateway</h1>"
"      <div class=\"status-indicator\" id=\"status\">"
"        <span class=\"dot\"></span>"
"        <span class=\"text\">Connecting...</span>"
"      </div>"
"    </header>"
"    <main>"
"      <section class=\"card\">"
"        <h2>Device Information</h2>"
"        <div class=\"info-grid\">"
"          <div class=\"info-item\"><label>Device</label><span id=\"info-device\">-</span></div>"
"          <div class=\"info-item\"><label>Firmware</label><span id=\"info-firmware\">-</span></div>"
"          <div class=\"info-item\"><label>Board</label><span id=\"info-board\">-</span></div>"
"          <div class=\"info-item\"><label>Uptime</label><span id=\"info-uptime\">-</span></div>"
"          <div class=\"info-item\"><label>Free Heap</label><span id=\"info-heap\">-</span></div>"
"        </div>"
"      </section>"
"      <section class=\"card\">"
"        <h2>Network Status</h2>"
"        <div class=\"info-grid\">"
"          <div class=\"info-item\"><label>WiFi Status</label><span id=\"info-wifi-status\">-</span></div>"
"          <div class=\"info-item\"><label>SSID</label><span id=\"info-ssid\">-</span></div>"
"          <div class=\"info-item\"><label>IP Address</label><span id=\"info-ip\">-</span></div>"
"          <div class=\"info-item\"><label>RSSI</label><span id=\"info-rssi\">-</span></div>"
"        </div>"
"        <a href=\"/config\" class=\"btn btn-primary\">Configure Network</a>"
"      </section>"
"      <section class=\"card\">"
"        <h2>DMX Output</h2>"
"        <div class=\"info-grid\">"
"          <div class=\"info-item\"><label>Output 1</label><span id=\"info-out1\">-</span></div>"
"          <div class=\"info-item\"><label>Output 2</label><span id=\"info-out2\">-</span></div>"
"        </div>"
"      </section>"
"    </main>"
"    <footer>"
"      <p>LuxDMX v2.0.0 | <a href=\"https://github.com/LuxDMX\" target=\"_blank\">GitHub</a></p>"
"    </footer>"
"  </div>"
"  <script src=\"/assets/app.js\"></script>"
"</body>"
"</html>";

// Config page HTML
static const char config_html[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"  <meta charset=\"UTF-8\">"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"  <title>Network Configuration - LuxDMX</title>"
"  <link rel=\"stylesheet\" href=\"/assets/style.css\">"
"</head>"
"<body>"
"  <div class=\"container\">"
"    <header>"
"      <h1>Network Configuration</h1>"
"      <a href=\"/\" class=\"btn btn-secondary\">Back to Dashboard</a>"
"    </header>"
"    <main>"
"      <section class=\"card\">"
"        <h2>WiFi Station Mode</h2>"
"        <form id=\"wifi-form\">"
"          <div class=\"form-group\">"
"            <label for=\"ssid\">SSID</label>"
"            <div class=\"input-group\">"
"              <select id=\"ssid\" name=\"wifi_ssid\" required>"
"                <option value=\"\">Scanning...</option>"
"              </select>"
"              <button type=\"button\" id=\"scan-btn\" class=\"btn btn-secondary\">Scan</button>"
"            </div>"
"          </div>"
"          <div class=\"form-group\">"
"            <label for=\"password\">Password</label>"
"            <input type=\"password\" id=\"password\" name=\"wifi_password\" placeholder=\"Enter WiFi password\">"
"          </div>"
"          <div class=\"form-group\">"
"            <label for=\"mode\">Mode</label>"
"            <select id=\"mode\" name=\"wifi_mode\">"
"              <option value=\"0\">Station Only</option>"
"              <option value=\"1\">Access Point Only</option>"
"              <option value=\"2\">Station + AP</option>"
"            </select>"
"          </div>"
"          <button type=\"submit\" class=\"btn btn-primary\">Save & Connect</button>"
"        </form>"
"        <div id=\"wifi-status\" class=\"status-message\"></div>"
"      </section>"
"      <section class=\"card\">"
"        <h2>Device Settings</h2>"
"        <form id=\"device-form\">"
"          <div class=\"form-group\">"
"            <label for=\"hostname\">Hostname</label>"
"            <input type=\"text\" id=\"hostname\" name=\"hostname\" value=\"luxdmx\">"
"          </div>"
"          <div class=\"form-group\">"
"            <label for=\"brightness\">LED Brightness (%)</label>"
"            <input type=\"range\" id=\"brightness\" name=\"led_brightness\" min=\"0\" max=\"100\" value=\"100\">"
"            <span id=\"brightness-value\">100</span>"
"          </div>"
"          <button type=\"submit\" class=\"btn btn-primary\">Save Settings</button>"
"        </form>"
"        <div id=\"device-status\" class=\"status-message\"></div>"
"      </section>"
"      <section class=\"card\">"
"        <h2>Advanced</h2>"
"        <button id=\"reboot-btn\" class=\"btn btn-danger\">Reboot Device</button>"
"        <button id=\"reset-btn\" class=\"btn btn-danger\">Factory Reset</button>"
"      </section>"
"    </main>"
"    <footer>"
"      <p>LuxDMX v2.0.0 | <a href=\"https://github.com/LuxDMX\" target=\"_blank\">GitHub</a></p>"
"    </footer>"
"  </div>"
"  <script src=\"/assets/app.js\"></script>"
"</body>"
"</html>";

const char* web_frontend_get_index(void) {
    return index_html;
}

const char* web_frontend_get_config(void) {
    return config_html;
}

// Setup page HTML
static const char setup_html[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"  <meta charset=\"UTF-8\">"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"  <title>WiFi Setup - LuxDMX</title>"
"  <link rel=\"stylesheet\" href=\"/assets/style.css\">"
"</head>"
"<body>"
"  <div class=\"container setup-container\">"
"    <header>"
"      <h1>LuxDMX Gateway</h1>"
"      <p class=\"subtitle\">First-time Setup</p>"
"    </header>"
"    <main>"
"      <section class=\"card\">"
"        <h2>Connect to WiFi</h2>"
"        <p>Enter your WiFi credentials to connect the device to your network.</p>"
"        <form id=\"setup-form\">"
"          <div class=\"form-group\">"
"            <label for=\"ssid\">WiFi Network (SSID)</label>"
"            <div class=\"input-group\">"
"              <select id=\"ssid\" name=\"ssid\" required>"
"                <option value=\"\">Scanning...</option>"
"              </select>"
"              <button type=\"button\" id=\"scan-btn\" class=\"btn btn-secondary\">Scan</button>"
"            </div>"
"          </div>"
"          <div class=\"form-group\">"
"            <label for=\"psk\">Password</label>"
"            <input type=\"password\" id=\"psk\" name=\"psk\" placeholder=\"Enter WiFi password\" autocomplete=\"off\">"
"          </div>"
"          <button type=\"submit\" class=\"btn btn-primary btn-block\">Connect</button>"
"        </form>"
"        <div id=\"setup-status\" class=\"status-message\"></div>"
"      </section>"
"    </main>"
"    <footer>"
"      <p>LuxDMX v2.0.0</p>"
"    </footer>"
"  </div>"
"  <script>"
"    // Scan for networks on load"
"    async function scanNetworks() {"
"      const select = document.getElementById('ssid');"
"      select.innerHTML = '<option value=\"\">Scanning...</option>';"
"      try {"
"        const resp = await fetch('/wifi/scan');"
"        const networks = await resp.json();"
"        select.innerHTML = '<option value=\"\">Select network...</option>';"
"        networks.forEach(n => {"
"          const opt = document.createElement('option');"
"          opt.value = n.ssid;"
"          opt.textContent = n.ssid + ' (' + n.rssi + ' dBm)' + (n.authmode ? ' 🔒' : '');"
"          select.appendChild(opt);"
"        });"
"      } catch (e) {"
"        select.innerHTML = '<option value=\"\">Scan failed - enter manually</option>';"
"      }"
"    }"
"    document.getElementById('scan-btn').addEventListener('click', scanNetworks);"
"    scanNetworks();"
"    // Form submit"
"    document.getElementById('setup-form').addEventListener('submit', async (e) => {"
"      e.preventDefault();"
"      const form = e.target;"
"      const btn = form.querySelector('button[type=submit]');"
"      const status = document.getElementById('setup-status');"
"      btn.disabled = true;"
"      btn.textContent = 'Connecting...';"
"      status.textContent = '';"
"      status.className = 'status-message';"
"      const formData = new FormData(form);"
"      try {"
"        const resp = await fetch('/setup', {"
"          method: 'POST',"
"          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },"
"          body: new URLSearchParams(formData)"
"        });"
"        const data = await resp.json();"
"        if (resp.ok) {"
"          status.textContent = data.message || 'WiFi saved, rebooting...';"
"          status.className = 'status-message success';"
"        } else {"
"          status.textContent = data.message || 'Failed to save WiFi';"
"          status.className = 'status-message error';"
"        }"
"      } catch (err) {"
"        status.textContent = 'Error: ' + err.message;"
"        status.className = 'status-message error';"
"      }"
"      btn.disabled = false;"
"      btn.textContent = 'Connect';"
"    });"
"  </script>"
"</body>"
"</html>";

const char* web_frontend_get_setup(void) {
    return setup_html;
}